apiVersion: v1
kind: Pod
metadata:
  name: database-pod
  labels:
    component: web
spec:
  containers: 
    - name: client
      image: ddydeveloper/make-a-meet-database
      ports:
        - containerPort: 1433