apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations: 
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    nginx.ingress.kubernetes.io/session-cookie-name: route
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: 'letsencrypt-prod'
spec:
  tls:
    - hosts:
        - book-to-meet.com
        - www.book-to-meet.com
      secretName: book-to-meet-com
  rules:
    - host: book-to-meet.com
      http:
        paths:
          - path: /
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000
          - path: /users-api
            backend:              
              serviceName: users-api-cluster-ip-service
              servicePort: 8001
          - path: /meetings-api
            backend:              
              serviceName: meetings-api-cluster-ip-service
              servicePort: 8002
    - host: www.book-to-meet.com      
      http:
        paths:
          - path: /
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000
          - path: /users-api
            backend:              
              serviceName: users-api-cluster-ip-service
              servicePort: 8001
          - path: /meetings-api
            backend:              
              serviceName: meetings-api-cluster-ip-service
              servicePort: 8002
