version: '3'

services:
  seq-logs:
    restart: always      
    image: datalust/seq:latest
    container_name: seq-logs
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8005:80"
  sqlserver:
    restart: always
    image: make-a-meet/sqlserver
    build:
      dockerfile: Dockerfile
      context: ./database
    ports:
      - "1435:1433"
  client:
    restart: always
    image: make-a-meet/client
    build:
      dockerfile: Dockerfile
      context: ./client-app
    container_name: client
    environment:
      - USERS_API_URL=api;
      - MEETINGS_API_URL=api;
    ports:
      - "3005:3000"
    depends_on:
      - usersapi
      - meetingsapi
  usersapi:
    restart: always
    image: make-a-meet/usersapi
    build:
      dockerfile: Dockerfile
      context: ./users
    container_name: usersapi
    environment:
      - ConnectionStrings__UsersDb=Server=sqlserver;DataBase=Users;User Id=sa;Password=P@ssw0rd;Connection Timeout=30;
      - ConnectionStrings__Seq=http://seq-logs/
    ports:
      - "5001:8001"
    depends_on:
      - sqlserver
      - seq-logs
  meetingsapi:
    restart: always
    image: make-a-meet/meetingsapi
    build:
      dockerfile: Dockerfile
      context: ./meetings
    container_name: meetingsapi
    environment:
      - ConnectionStrings__MeetingsDb=Server=sqlserver;DataBase=Meetings;User Id=sa;Password=P@ssw0rd;Connection Timeout=30;
      - ConnectionStrings__Seq=http://seq-logs/
    ports:
      - "5002:8002"
    depends_on:
      - sqlserver
      - seq-logs